FROM arm64v8/ubuntu:18.04
ADD entry.sh /
RUN chmod +x /entry.sh
    && sed -i s@/ports.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list \
    && apt update \
    && apt install -y v4l-utils 

ENTRYPOINT ["/entry.sh"]
